### PR TITLE
Update scoring.py

### PR DESCRIPTION
**Pull request by aokugel**
changed field from dense_input to dense_3_input on scoring.py

#28

### CODE REVIEW

**Review by bbalakriz — APPROVED** [review]
LGTM.

**Comment by aokugel** [comment]
@bbalakriz thank you!  Is there anything else i need to do before the pr is merged?

**Comment by bbalakriz** [comment]
@aokugel, In my view, no further action is required. Let's wait to hear from a reviewer who has write access.

**Review by rsriniva — APPROVED** [review]

**Comment by rsriniva** [comment]
thanks folks. I am merging this.

**Pull request merged**
